"""initial structure

Revision ID: 06958cf23f5d
Revises: 
Create Date: 2024-10-28 12:32:45.983038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06958cf23f5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_password_reset_tokens'))
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_themes')),
    sa.UniqueConstraint('name', name=op.f('uq_themes_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('remember_token', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    sa.UniqueConstraint('uuid', name=op.f('uq_users_uuid'))
    )
    op.create_table('jwt_blocked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jwt_blocked_tokens_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jwt_blocked_tokens'))
    )
    with op.batch_alter_table('jwt_blocked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwt_blocked_tokens_jti'), ['jti'], unique=False)

    op.create_table('snaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(length=20), nullable=False),
    sa.Column('snap', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_snaps_language_id_languages'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_snaps_theme_id_themes'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_snaps_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snaps')),
    sa.UniqueConstraint('unique_code', name=op.f('uq_snaps_unique_code'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snaps')
    with op.batch_alter_table('jwt_blocked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwt_blocked_tokens_jti'))

    op.drop_table('jwt_blocked_tokens')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('password_reset_tokens')
    op.drop_table('languages')
    # ### end Alembic commands ###
