"""make cascade in foreignkey

Revision ID: 07d10504a099
Revises: 4ec164de1af8
Create Date: 2024-05-31 02:33:04.651731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d10504a099'
down_revision = '4ec164de1af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snaps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_snaps_theme_id_themes', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_snaps_theme_id_themes'), 'themes', ['theme_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snaps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_snaps_theme_id_themes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_snaps_theme_id_themes', 'themes', ['theme_id'], ['id'])

    # ### end Alembic commands ###
