"""rename snaps table columns

Revision ID: 20a28345b7dc
Revises: bf3fbcb598b6
Create Date: 2024-06-11 13:11:25.398072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20a28345b7dc'
down_revision = 'bf3fbcb598b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snap', sa.String(length=255), nullable=False))
        batch_op.alter_column('unique_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('image_base64')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_base64', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False))
        batch_op.alter_column('unique_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=False)
        batch_op.drop_column('snap')

    # ### end Alembic commands ###
