"""foreignkey in snaps table for theme_id

Revision ID: 4ec164de1af8
Revises: f7684a80411b
Create Date: 2024-05-31 00:35:12.979621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec164de1af8'
down_revision = 'f7684a80411b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_snaps_theme_id_themes'), 'themes', ['theme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snaps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_snaps_theme_id_themes'), type_='foreignkey')
        batch_op.drop_column('theme_id')

    # ### end Alembic commands ###
